apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  containers:
    - image: quay.io/coreos/etcd:v3.5.21
      name: etcd
      args:
        - "etcd"
        - "--data-dir"
        - "/data"
        - "--listen-client-urls"
        - "http://0.0.0.0:2379"
        - "--advertise-client-urls"
        - "http://10.0.0.21:2379"
      ports:
        - containerPort: 2379
          hostPort: 2379
      volumeMounts:
        - mountPath: /data
          name: etcd-data
  volumes:
    - name: etcd-data
      persistentVolumeClaim:
        claimName: etcd-data
