apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  containers:
    - image: gcr.io/etcd-development/etcd:v3.6.4
      name: etcd
      args:
        - "etcd"
        - "--listen-client-urls"
        - "http://0.0.0.0:2379"
        - "--advertise-client-urls"
        - "http://10.0.0.21:2379"
      ports:
        - containerPort: 2379
          hostPort: 2379
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: etcd-data
  volumes:
    - name: etcd-data
      persistentVolumeClaim:
        claimName: etcd-data
