apiVersion: v1
kind: Pod
metadata:
  labels:
    app: parseable
  name: parseable
spec:
  containers:
    - name: parseable
      image: docker.io/parseable/parseable:v0.9.0
      env:
        - name: P_FS_DIR
          value: /data
        - name: P_STAGING_DIR
          value: /staging
        - name: P_USERNAME
          value: parseable
        - name: P_PASSWORD
          value: parseable
      command:
        - "parseable"
        - "local-store"
      ports:
        - containerPort: 8000
          hostPort: 8000
      volumeMounts:
        - mountPath: /data
          name: parseable-data-pvc
        - mountPath: /staging
          name: parseable-staging-pvc
  volumes:
    - name: parseable-data-pvc
      persistentVolumeClaim:
        claimName: parseable-data
    - name: parseable-staging-pvc
      persistentVolumeClaim:
        claimName: parseable-staging
