apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  containers:
    - image: docker.io/jaegertracing/jaeger:2.5.0
      name: jaeger
      ports:
        - containerPort: 4317
          hostPort: 24317
        - containerPort: 4318
          hostPort: 24318
        - containerPort: 16686
          hostPort: 16686
