apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  containers:
    - name: grafana
      image: docker.io/grafana/grafana:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
