apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: docker.io/library/mongo:7.0.11
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
      ports:
        - containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-data-db-pvc
        - mountPath: /data/configdb
          name: mongodb-data-configdb-pvc
  volumes:
    - name: mongodb-data-db-pvc
      persistentVolumeClaim:
        claimName: mongodb-data-db
    - name: mongodb-data-configdb-pvc
      persistentVolumeClaim:
        claimName: mongodb-data-configdb
