apiVersion: v1
kind: Pod
metadata:
  labels:
    app: consul
  name: consul
spec:
  containers:
    - name: consul
      image: docker.io/hashicorp/consul:1.20.6
      args:
        - agent
        - -server
        - -ui
        - -bootstrap-expect
        - 1
        - -client
        - 0.0.0.0
      ports:
        - containerPort: 8500
          hostPort: 8500
      volumeMounts:
        - mountPath: /consul/data
          name: consul-data-pvc
  volumes:
    - name: consul-data-pvc
      persistentVolumeClaim:
        claimName: consul-data
