apiVersion: v1
kind: Pod
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  containers:
    - image: docker.io/library/elasticsearch:8.19.1
      name: elasticsearch
      env:
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "true"
        - name: cluster.routing.allocation.disk.watermark.low
          value: 512mb
        - name: cluster.routing.allocation.disk.watermark.high
          value: 256mb
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: 128mb
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
      ports:
        - containerPort: 9200
          hostPort: 9200
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data-pvc
        - mountPath: /usr/share/elasticsearch/logs
          name: elasticsearch-log-pvc
    - image: docker.io/library/kibana:8.18.0
      name: kibana
      env:
        - name: ELASTICSEARCH_HOSTS
          value: http://127.0.0.1:9200
      ports:
        - containerPort: 5601
          hostPort: 5601
  volumes:
    - name: elasticsearch-data-pvc
      persistentVolumeClaim:
        claimName: elasticsearch-data
    - name: elasticsearch-log-pvc
      persistentVolumeClaim:
        claimName: elasticsearch-log
