apiVersion: v1
kind: Pod
metadata:
  labels:
    app: parca
  name: parca
spec:
  containers:
    - name: parca
      image: ghcr.io/parca-dev/parca:v0.21.0
      command:
        - "/parca"
      args:
        - "--config-path=/parca.yaml"
        - "--log-level=debug"
      ports:
        - containerPort: 7070
          hostPort: 7070
      volumeMounts:
        - mountPath: /data
          name: parca-data-pvc
        - mountPath: /parca.yaml
          name: parca-config
  volumes:
    - name: parca-data-pvc
      persistentVolumeClaim:
        claimName: parca-data
    - hostPath:
        path: /home/aaron/workspace/manifests/parca.yaml
        type: File
      name: parca-config
