apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
    - name: mysql
      image: docker.io/library/mysql:8.0.32
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      ports:
        - containerPort: 3306
          hostPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data-pvc
  volumes:
    - name: mysql-data-pvc
      persistentVolumeClaim:
        claimName: mysql-data
