apiVersion: v1
kind: Pod
metadata:
  labels:
    app: plantuml
  name: plantuml
spec:
  containers:
    - name: plantuml
      image: docker.io/plantuml/plantuml-server:v1.2025.4
      ports:
        - containerPort: 8080
          hostPort: 8181
      volumeMounts:
        - mountPath: /tmp/jetty
          name: plantuml-temp
  volumes:
    - name: plantuml-temp
      emptyDir:
        type: Directory
