apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  containers:
    - name: cassandra
      image: docker.io/library/cassandra:5.0.5
      args:
        - cassandra
        - -f
      env:
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 128M
      ports:
        - containerPort: 7000
          hostPort: 7000
        - containerPort: 9160
          hostPort: 9160
        - containerPort: 9042
          hostPort: 9042
      volumeMounts:
        - mountPath: /var/lib/cassandra
          name: cassandra-data-pvc
        - mountPath: /tmp
          name: cassandra-temp
  volumes:
    - name: cassandra-data-pvc
      persistentVolumeClaim:
        claimName: cassandra-data
    - name: cassandra-temp
      emptyDir:
        type: Directory
