apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  containers:
    - name: kafka
      image: docker.io/apache/kafka-native:4.0.0
      env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@localhost:9093
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.64.6:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        - name: KAFKA_LOG_DIR
          value: /var/lib/kafka/data
        - name: KAFKA_HEAP_OPTS
          value: -Xmx512M -Xms512M -Xmn128M
      ports:
        - containerPort: 9092
          hostPort: 9092
      volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data-pvc
        - mountPath: /etc/kafka/secrets
          name: kafka-secrets-pvc
        - mountPath: /mnt/shared/config
          name: kafka-shared-config-pvc
    - name: redpanda
      image: docker.io/redpandadata/console:v3.1.2
      ports:
        - containerPort: 8080
          hostPort: 8090
      env:
        - name: KAFKA_BROKERS
          value: 127.0.0.1:9092
  volumes:
    - name: kafka-data-pvc
      persistentVolumeClaim:
        claimName: kafka-data
    - name: kafka-secrets-pvc
      persistentVolumeClaim:
        claimName: kafka-secrets
    - name: kafka-shared-config-pvc
      persistentVolumeClaim:
        claimName: kafka-shared-config
