apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:17.2
      env:
        - name: POSTGRES_PASSWORD
          value: "123456"
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-pvc
  volumes:
    - name: postgres-data-pvc
      persistentVolumeClaim:
        claimName: postgres-data
