apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
spec:
  containers:
    - name: redis
      image: docker.io/library/redis:8.4.0
      args:
        - redis-server
        - --appendonly
        - yes
      ports:
        - containerPort: 6379
          hostPort: 6379
      volumeMounts:
        - mountPath: /data
          name: redis-data-pvc
  volumes:
    - name: redis-data-pvc
      persistentVolumeClaim:
        claimName: redis-data
